{
  pkgs,
  lib,
  processIcons,
  fallbackIcon,
  maxIconsPicker,
  splashTips ? [],
  splashTimeout ? 10,
  prefix ? "`",
}: let
  iconsGo = pkgs.writeText "icons_generated.go" ''
    package main

    // Generated by Nix from process-icons.nix and lib-claude.sh constants.
    // Do not edit manually.

    var iconMap = map[string]string{
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: "	${builtins.toJSON k}: ${builtins.toJSON v},") processIcons)}
    }

    var fallbackIcon = ${builtins.toJSON fallbackIcon}
    var maxIconsPicker = ${maxIconsPicker}

    // Claude status icons (from lib-claude.sh)
    var claudeSpinnerFrames = []string{"󰪞", "󰪟", "󰪠", "󰪡", "󰪢", "󰪣", "󰪤", "󰪥"}
    var claudeIconWaiting = "󰔟"
    var claudeIconCompacting = "󰡍"
    var claudeIconDone = "󰸞"
    var claudeIconIdle = "󰒲"
    var claudeIconError = "󰅚"
    var claudeIconDenied = "󰔟" // same clock as waiting, different color
    var claudeIconBG = "󰅐" // nf-md-timer_sand — background shells still running

    // Default icons (overridden by env vars or tmux options at runtime)
    var iconSession = ""
    var iconDir = ""
    var iconBranch = ""
    var iconHost = ""
    var iconProcs = "󰀻"
    var iconCPU = ""
    var iconMem = ""
    var iconRemote = ""
  '';

  tipsGo = pkgs.writeText "tips_generated.go" ''
    package main

    // Generated by Nix from programs.tmux-og.splash.*. Do not edit manually.

    var splashTips = []tip{
    ${lib.concatMapStringsSep "\n" (t: "	{Key: ${builtins.toJSON t.key}, Label: ${builtins.toJSON t.label}},") splashTips}
    }

    var splashPrefix = ${builtins.toJSON prefix}

    var splashTimeoutSec = ${toString splashTimeout}
  '';

  src = pkgs.runCommand "picker-src" {} ''
    cp -r ${lib.cleanSource ./.} $out
    chmod -R u+w $out
    cp ${iconsGo} $out/icons_generated.go
    cp ${tipsGo} $out/splash/tips_generated.go
    rm -f $out/default.nix
  '';
in
  pkgs.buildGoModule {
    pname = "tmux-og-go-tools";
    version = "0.1.0";
    inherit src;
    vendorHash = "sha256-Z72w5oQsXFFqvkK1ndOTtu7AonXtxAM55JhzgJV5Usc=";
    subPackages = ["." "splash" "statusline" "enrichcard" "agentdetect" "sessionres" "remotebridge" "remotebridge/cmd/daemon" "remotebridge/cmd/renderer" "remotebridge/cmd/ctl"];
    ldflags = ["-s" "-w"]; # strip debug info for smaller binary + faster startup
    # Binary name matches pname (Go module produces "picker" by default)
    postInstall = ''
      mv $out/bin/picker $out/bin/tmux-picker-generate
      mv $out/bin/splash $out/bin/tmux-splash
      mv $out/bin/statusline $out/bin/tmux-statusline
      mv $out/bin/enrichcard $out/bin/tmux-enrich-card
      mv $out/bin/agentdetect $out/bin/agent-detect
      mv $out/bin/sessionres $out/bin/tmux-session-resources
      mv $out/bin/remotebridge $out/bin/og-remote-bridge
      mv $out/bin/daemon $out/bin/og-remote-bridge-daemon
      mv $out/bin/renderer $out/bin/og-remote-bridge-renderer
      mv $out/bin/ctl $out/bin/og-remote-bridge-ctl
    '';
  }
