#!/usr/bin/env bash
# Equivalence check: every variant, run against an identical fresh fixture,
# must print the same stdout, exit the same way and leave byte-identical
# window/session options (fixture.sh snapshot). A second run of each must
# change nothing (the steady state the timings measure).
#
#   equiv.sh [VARIANT...]      default: A B C D, plus E when built
set -euo pipefail

# shellcheck source=/dev/null  # sibling helper
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
resolve_build
resolve_bash

if (($# > 0)); then
	variants=("$@")
else
	variants=(A B C D)
	[[ -x $SPIKE_DIR/.build/e-go-head ]] && variants+=(E)
fi

out="$(mktemp -d /tmp/og-bakeoff-equiv.XXXX)"
root="$out/fx"
trap '"$SPIKE_DIR/fixture.sh" down "$root" || true; rm -rf "$out"' EXIT

status=0
for v in "${variants[@]}"; do
	"$SPIKE_DIR/fixture.sh" up "$root"
	variant_cmd "$v"
	(
		# shellcheck source=/dev/null  # generated by fixture.sh up
		source "$root/env"
		set +e
		"${VCMD[@]}" "${OG_ARGS[@]}" >"$out/$v.stdout" 2>"$out/$v.stderr"
		echo "$?" >"$out/$v.exit"
	)
	"$SPIKE_DIR/fixture.sh" snapshot "$root" >"$out/$v.snap"
	(
		# shellcheck source=/dev/null
		source "$root/env"
		"${VCMD[@]}" "${OG_ARGS[@]}" >/dev/null 2>&1
	) || true
	"$SPIKE_DIR/fixture.sh" snapshot "$root" >"$out/$v.snap2"
	"$SPIKE_DIR/fixture.sh" down "$root"

	verdict=PASS
	[[ $(<"$out/$v.exit") == 0 ]] || verdict="FAIL(exit $(<"$out/$v.exit"): $(head -c 200 "$out/$v.stderr"))"
	[[ ! -s $out/$v.stdout ]] || verdict="FAIL(stdout not empty)"
	cmp -s "$out/$v.snap" "$out/$v.snap2" || verdict="FAIL(second run changed options)"
	if [[ $v != A ]]; then
		cmp -s "$out/A.snap" "$out/$v.snap" || {
			verdict="FAIL(options differ from A)"
			diff "$out/A.snap" "$out/$v.snap" | head -20 || true
		}
	fi
	printf '%s %s (options set: %s lines, stdout bytes: %s)\n' "$v" "$verdict" "$(wc -l <"$out/$v.snap")" "$(wc -c <"$out/$v.stdout")"
	[[ $verdict == PASS ]] || status=1
done
exit "$status"
