#!/usr/bin/env bash
# Keystroke-echo latency with each variant as the 1 s status job, on a scratch
# server with a real status-drawing client attached (the shape of
# tests/perf/keystroke-latency.sh, minus the remote bridge: this measures the
# status job's own cost on the tmux server thread, which is what the job is
# accused of). picker/latencyprobe types into a `cat` pane over a control-mode
# client and times the echo.
#
#   [INTERVAL=30ms] latency.sh [SAMPLES] [VARIANTS...]   default: 600 samples; none A B C D E
#
# Run inside `nix develop` after ./build.sh. `none` is a status line with no
# job, the floor every variant is compared to.
set -euo pipefail

# shellcheck source=/dev/null  # sibling helper
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
resolve_build
resolve_bash

samples="${1:-600}"
shift || true
variants=("$@")
((${#variants[@]} > 0)) || variants=(none A B C D E)

work="$(mktemp -d /tmp/og-bakeoff-lat.XXXX)"
root="$work/fx"
cleanup() {
	TMUX_TMPDIR="$root/run" "$root/bin/tmux" -L obs kill-server 2>/dev/null || true
	"$SPIKE_DIR/fixture.sh" down "$root" || true
	rm -rf "$work"
}
trap cleanup EXIT
trap 'exit 130' INT TERM

(cd "$REPO_ROOT/picker" && go build -o "$work/latencyprobe" ./latencyprobe)

"$SPIKE_DIR/fixture.sh" up "$root"
# shellcheck source=/dev/null  # generated by fixture.sh up
source "$root/env"
tm() { "$root/bin/tmux" -L probe "$@"; }

# The status job runs with the server's environment, so hand the variants what
# a shell would export for them.
for var in CLAUDE_STATUS_DIR CLAUDE_NOW RECONCILE_BIN ISSUE_STAMP_BIN REFLOW_BIN AGENT_DETECT_BIN \
	OG_LIB_ICONS OG_LIB_CLAUDE OG_LIB_LOG OG_AGENT_COMMANDS OG_MAX_ICONS PATH; do
	tm set-environment -g "$var" "${!var}"
done

tm new-session -d -s lat -x 200 -y 50 -c "$root/nogit/n1" cat
tm set -w -t lat: @branch ""
pane="$(tm list-panes -t lat -F '#{pane_id}')"
tm set -g status on
tm set -g status-interval 1

# The status-drawing client, attached from a second server as the harness does.
TERM=xterm-256color TMUX_TMPDIR="$root/run" "$root/bin/tmux" -L obs -f /dev/null new-session -d -x 200 -y 52 \
	"env -u TMUX $root/bin/tmux -L probe attach -t alpha"

args="${OG_ARGS[0]} '' ${OG_ARGS[2]} '' ${OG_ARGS[4]} ${OG_ARGS[5]}"
echo "== latency: $samples samples per variant, variants: ${variants[*]}"
load_report
for v in "${variants[@]}"; do
	if [[ $v == none ]]; then
		tm set -g 'status-format[0]' "x"
	else
		variant_cmd "$v"
		"${VCMD[@]}" "${OG_ARGS[@]}"
		tm set -g 'status-format[0]' "#(echo; ${VCMD[*]} $args)"
	fi
	sleep 3
	"$work/latencyprobe" -tmux "$root/bin/tmux" -L probe -t lat -pane "$pane" \
		-n "$samples" -interval "${INTERVAL:-30ms}" -label "$v"
done
load_report
